// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    List: typeof import('./src/components/list.vue')['default']
    Score: typeof import('./src/components/Score.vue')['default']
    Scroe: typeof import('./src/components/Score.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
  }
}
